# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatbotApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatbotApp

  #Auto Layout library
  pod 'SnapKit', '~> 4.0.0'

  #Send Message TextInput
  pod 'Toolbar'

  #Messages TableView
  pod 'ReverseExtension'

  #Connect with DialogFlow
  pod 'Kommunicate'

  pod 'KakaoSDK'
end
